# Generated by Django 4.1.2 on 2024-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_Cliente', models.AutoField(db_column='id_Cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=30)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_Insumo', models.AutoField(db_column='idInsumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Insumos/', verbose_name='Foto del Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Maceteros',
            fields=[
                ('id_Macetero', models.AutoField(db_column='idMacetero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Maceteros/', verbose_name='Foto del Macetero')),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id_planta', models.AutoField(db_column='idPlanta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Plantas/', verbose_name='Foto de la planta')),
            ],
        ),
    ]
